- hosts: nmt_server
  vars:
      user_name: fanyi
      decoder_version: 8.1.4
      dest_decoder_path: /data/decoder
      localhost_decoder_path: /home/fanyi/ansible
  tasks:
    - name: 1.Copying newest docker image to Remote server....
      synchronize: src={{localhost_decoder_path}}/image/newtranx_server-gpu.v{{decoder_version}}.tar.gz dest={{dest_decoder_path}}/
      delegate_to: localhost

    - name: 2.Copying scripts to Remote Server....
      copy:
       src: "{{ item }}"
       dest: "{{ dest_decoder_path }}"
       mode: 0777
      with_fileglob:
       - "{{localhost_decoder_path}}/ansible_scripts/*.sh"

    - name: 2.1.Copying specific volumes file to dest.
      copy: src={{localhost_decoder_path}}/ansible_scripts/inventory/{{server_id}}.volumes dest={{dest_decoder_path}}/volumes

    - name: 3.Loading Docker image...
      shell: "./load.sh {{decoder_version}}"
      args:
       chdir: "{{ dest_decoder_path }}"

    - name: 4.Restart dockers
      shell: "./remove_online_all.sh {{decoder_version}}"
      args:
       chdir: "{{ dest_decoder_path }}"

