- hosts: nmt_server
  vars:
      user_name: newtranx
      decoder_version: 8.1.5
      dest_decoder_path: /home/{{user_name}}/decoder
  tasks:
    - name: 1.Restart dockers
      shell: "./remove_online.sh {{target_volume}} {{decoder_version}}"
      args:
       chdir: "{{ dest_decoder_path }}"
