- hosts: nmt_server
  vars:
      user_name: newtranx
<<<<<<< HEAD
      decoder_version: 8.1.5
=======
      decoder_version: 8.0.9
>>>>>>> 39fd456a193e17a61702ac0b7a9bc41b1683548a
      dest_decoder_path: /home/{{user_name}}/decoder
  tasks:
    - name: 1.Restart dockers
      shell: "./remove_online.sh {{target_volume}} {{decoder_version}}"
      args:
       chdir: "{{ dest_decoder_path }}"
